# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'About GIRAF',   url: '/about/'}
- {name: 'Our Apps',      url: '/apps/'}
- {name: 'History',       url: '/history/'}
- {name: 'For Students',  url: '/students/'}
- {name: 'Contact',       url: '/contact/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/aau-giraf'}
- {icon: 'envelope', link: 'mailto:nbha@cs.aau.dk'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'